Replace `kubeval` with `kubeconform`
The `kubeval` package is no longer maintained, `kubeconform` was developed to replace it.

```
Error: kubeval has been disabled because it is not maintained upstream!
```
https://github.com/instrumenta/kubeval/issues/268#issuecomment-902128481