fix(deps): install Tcl/Tk without linking binaries
Prevents errors like the following:
```
Error: Cannot install tcl-tk because conflicting formulae are installed.
  the_platinum_searcher: because both install `pt` binaries

Please `brew unlink the_platinum_searcher` before continuing.
```